# Data Import

Data & Analytics | Team: Danny Schönhals & Athithya Mariyanayagam | TH Nuernberg

## 0) Imports

In [14]:
import numpy as np
import pandas as pd
from pathlib import Path

## 1) Autonomous Vehicle Survey of Bicyclists and Pedestrians in Pittsburgh

### 1a) Compare the data dictionaries for the survey data for 2017 and 2019.
What variables are common, where are differences?

In [15]:
print("2017 Data Dictionary:")
av2017 = pd.read_csv("data/av_survey_data/avsurvey2017datadictionary.csv", encoding="latin-1") # load the 2017 data dictionary.csv file using pandas read_csv function and specify the encoding as latin-1
print(av2017.head(10))
print("Shape of 2017 Data Dictionary:", av2017.shape)

print("\n2019 Data Dictionary:")
av2019 = pd.read_csv("data/av_survey_data/avsurvey2019datadictionary.csv", encoding="latin-1") # load the 2019 data dictionary.csv file using pandas read_csv function and specify the encoding as latin-1
print(av2019.head(10))
print("Shape of 2019 Data Dictionary:", av2019.shape)

2017 Data Dictionary:
               FieldName                            Description or Question  \
0            Response ID                                        Response ID
1             Start Date                           Date/time survey started
2               End Date                         Date/time survey completed
3                 Status                                             Status
4            Source Type                                        Source Type
5     InteractPedestrian  Have you interacted with an AV while riding yo...
6        InteractBicycle  Have you interacted with an AV while using sid...
7  CircumstancesFreeText  If you have had AV interactions, what were the...
8     CircumstancesCoded                                Circumstances Coded
9  FeelingsProvingGround  How do you feel right now about the use of Pit...

                                  Range of Responses
0                                                 ID
1                           Date/time survey started
2                         Date/time survey completed
3                                          Completed
4                                Survey link; social
5                                  No; Not Sure; Yes
6                                  No; Not Sure; Yes
7  Question asked, but results not shared as publ...
8  Free-text coded by Pitt UCSUR. Codes: 1. expre...
9  Approve; Somewhat Approve; Neutral; Somewhat D...
Shape of 2017 Data Dictionary: (25, 3)

2019 Data Dictionary:
          FieldName                            Description or Question  \
0      RespondentID                                      Respondent ID
1         StartDate                                Date survey started
2           EndDate                              Date Survey Completed
3   FamiliarityNews  To what extent have you been paying attention ...
4   FamiliarityTech  How familiar are you with the technology behin...
5     SharedCyclist  Have you shared the road with an Autonomous Ve...
6  SharedPedestrian  Have you been near an AV while walking or usin...
7               NaN  If you answered YES to either question; were t...
8               NaN  Please share any positive experiences that you...
9               NaN  Please share any negative experiences that you...

                                  Range of Responses
0                                                NaN
1                                                NaN
2                                                NaN
3  To a large extent; to a moderate extent; to so...
4  Extremely familiar; mostly familiar; somewhat ...
5                                  yes; no; not sure
6                                  yes; no; not sure
7  Question asked; but results not shared as publ...
8  Question asked; but results not shared as publ...
9  Question asked; but results not shared as publ...
Shape of 2019 Data Dictionary: (28, 3)

In [16]:
# What variables are in common and where do they differ?
# find the common variables between the two data dictionaries by taking the intersection of the sets of field names
# in order to use the intersection method, we need to convert the "FieldName" columns of both dataframes into sets using the set() function. 
common_vars = set(av2017["FieldName"]).intersection(set(av2019["FieldName"])) 

print("\nCommon Variables between 2017 and 2019 Data Dictionaries:")
print(common_vars)

only_2017 = set(av2017["FieldName"]) - set(av2019["FieldName"]) # find the variables that are only in the 2017 data  by taking the difference of the sets of field names
only_2019 = set(av2019["FieldName"]) - set(av2017["FieldName"]) # find the variables that are only in the 2019 data by taking the difference of the sets of field names
#
print("\nVariables only in 2017:", only_2017)
print("\nVariables only in 2019:", only_2019)

Common Variables between 2017 and 2019 Data Dictionaries:
{'ZipCode'}

Variables only in 2017: {' End Date', 'Response ID', 'InteractPedestrian', 'SafetyHuman', 'RegulationSchoolZone', 'CircumstancesCoded', 'RegulationTesting', 'AVSafetyPotential', ' Status', 'SafetyAV', 'FamiliarityTechnoology', 'PayingAttentionAV', ' Start Date', 'AdvocacyIssues', ' Source Type', 'CircumstancesFreeText', 'MoreToShare', 'FeelingsProvingGround', 'RegulationShareData', 'BikePghPosition', 'BikePghElaborate', 'RegulationSpeed', 'InteractBicycle', 'OtherRegulations'}

Variables only in 2019: {nan, 'SharedPedestrian', 'ReportSafetyIncident', 'SmartphoneOwner', 'RespondentID', 'BikePghMember', 'SchoolZoneManual', 'ArizonaCrash', 'FamiliarityTech', 'SharePerformanceData', 'ProvingGround', 'Speed25Mph', 'AvImpact', 'AutoOwner', 'ShareTripData', 'SafeHuman', 'Age', 'StartDate', 'SharedCyclist', 'TwoEmployeesAv', 'FamiliarityNews', 'SafeAv', 'EndDate'}

#### Same in the two datasets: 
- Same amount of columns and column names
- Share the same metadata (StartDate, EndDate, RespondentID), but with different naming in the two csv-files (better naming in 2019, no spaces)
- Field ZipCode is identical in both files

#### Different in the two datasets:
- Different amount of rows (25 in 2017- and 28 in 2019-datadictionary)
-> some variables got added
- Several fields were renamed: SafetyAV→SafeAv, InteractBicycle→SharedCyclist, InteractPedestrian→SharedPedestrian
- Some fields were split: single FamiliarityTechnoology (typo in 2017) → FamiliarityNews + FamiliarityTech in 2019
- 2019 added new demographics: Age, AutoOwner, SmartphoneOwner, BikePghMembe
- There are NaNs for FieldNames for 2019 that aren't there in 2017

### 1b) Combine the data sets with member and public data for 2017.
Add a column "BikePghMember" with the possible values "yes" or "no". Save the resulting dataset as csv.

In [17]:
member2017 = pd.read_csv("data/av_survey_data/avsurvey2017data_members.csv") #load data for 2017 members
public2017 = pd.read_csv("data/av_survey_data/avsurvey2017data_public.csv") #load data for 2017 public

columns_member2017 = member2017.columns # get the column names of the member2017 dataframe using the columns attribute and store them in a variable called columns_member2017
print("\nColumns in 2017 Member Data:")
print(columns_member2017)
print("\nShape of 2017 Member Data:", member2017.shape)
columns_public2017 = public2017.columns # get the column names of the public2017 dataframe using the columns attribute and store them in a variable called columns_public2017
print("\nColumns in 2017 Public Data:")
print(columns_public2017)
print("\nShape of 2017 Public Data:", public2017.shape)

# add the column "BikePghMember" to member2017 with "yes" and to public2017 with "no"
member2017["BikePghMember"] = "yes" # add a new column called "BikePghMember" to the member2017 dataframe and set its value to "yes" for all rows
print("\n Shape of 2017 Member Data after adding BikePghMember column:", member2017.shape)
public2017["BikePghMember"] = "no" # add a new column called "BikePghMember" to the public2017 dataframe and set its value to "no" for all rows
print("\n Shape of 2017 Public Data after adding BikePghMember column:", public2017.shape)

# The columns are the same, so we can concatenate the two datasets
# concatenate the member2017 and public2017 dataframes using the concat function from pandas and specify ignore_index=True to reset the index of the resulting dataframe. Store the concatenated dataframe in a variable called av2017_data
av2017_data = pd.concat([member2017, public2017], ignore_index=True) 
print("\nCombined 2017 Data Shape:", av2017_data.shape)

# save concatenated data to csv file
av2017_data.to_csv("data/av_survey_data/avsurvey2017data.csv", encoding = "utf-8", index=False)
av2017_data.head()

Columns in 2017 Member Data:
Index(['Response ID', 'Start Date', 'End Date', 'Status', 'Source Type',
       'InteractPedestrian', 'InteractBicycle', 'CircumstancesCoded',
       'FeelingsProvingGround', 'SafetyHuman', 'SafetyAV', 'AVSafetyPotential',
       'RegulationTesting', 'RegulationSpeed', 'RegulationSchoolZone',
       'RegulationShareData', 'AdvocacyIssues', 'BikePghPosition',
       'PayingAttentionAV', 'FamiliarityTechnoology', 'ZipCode'],
      dtype='object')

Shape of 2017 Member Data: (341, 21)

Columns in 2017 Public Data:
Index(['Response ID', 'Start Date', 'End Date', 'Status', 'Source Type',
       'InteractPedestrian', 'InteractBicycle', 'CircumstancesCoded',
       'FeelingsProvingGround', 'SafetyHuman', 'SafetyAV', 'AVSafetyPotential',
       'RegulationTesting', 'RegulationSpeed', 'RegulationSchoolZone',
       'RegulationShareData', 'AdvocacyIssues', 'BikePghPosition',
       'PayingAttentionAV', 'FamiliarityTechnoology', 'ZipCode'],
      dtype='object')

Shape of 2017 Public Data: (813, 21)

 Shape of 2017 Member Data after adding BikePghMember column: (341, 22)

 Shape of 2017 Public Data after adding BikePghMember column: (813, 22)

Combined 2017 Data Shape: (1154, 22)

,Response ID,Start Date,End Date,Status,Source Type,InteractPedestrian,InteractBicycle,CircumstancesCoded,FeelingsProvingGround,SafetyHuman,...,RegulationTesting,RegulationSpeed,RegulationSchoolZone,RegulationShareData,AdvocacyIssues,BikePghPosition,PayingAttentionAV,FamiliarityTechnoology,ZipCode,BikePghMember
0,259886900,02/15/2017 12:11:03 PM PST,02/15/2017 12:12:27 PM PST,COMPLETE,Survey Link,Yes,Yes,9.0,Disapprove,1,...,Yes,Yes,Yes,Yes,Disagree,Neither Support nor Oppose,Not at all,Somewhat familiar,15209.0,yes
1,259914050,02/15/2017 1:34:14 PM PST,02/15/2017 1:38:44 PM PST,COMPLETE,Survey Link,No,Yes,9.0,Somewhat Disapprove,3,...,Yes,Yes,No,No,Disagree,Neither Support nor Oppose,To a moderate extent,Somewhat familiar,15090.0,yes
2,260012773,02/16/2017 6:00:29 AM PST,02/16/2017 6:06:31 AM PST,COMPLETE,Survey Link,Yes,Yes,9.0,Neutral,2,...,No,Yes,No,Yes,Disagree,Neither Support nor Oppose,To a moderate extent,Somewhat familiar,15212.0,yes
3,260023580,02/16/2017 9:08:32 AM PST,02/16/2017 9:15:00 AM PST,COMPLETE,Survey Link,No,No,9.0,Approve,4,...,Yes,Yes,No,Yes,Disagree,Actively Support,To a moderate extent,Mostly Unfamiliar,15206.0,yes
4,260023756,02/16/2017 9:12:19 AM PST,02/16/2017 9:27:38 AM PST,COMPLETE,Survey Link,No,No,9.0,Somewhat Approve,4,...,Yes,Yes,Yes,Yes,Agree,Actively Support,To a moderate extent,Somewhat familiar,15129.0,yes

### 1c) Check the combined data for missing values and anomalies.
Describe your findings.

In [18]:
# Check duplicates in the combined dataset
print("\nNumber of duplicate rows in combined 2017 data:", av2017_data.duplicated().sum())

# Count NaNs per column
print("Count of NaN values per column in 2017 Data:")
# use the isnull() method to check for NaN values in the av2017_data dataframe and then use the sum() method to count the number of NaN values in each column. 
print(av2017_data.isnull().sum()) 

print("\n Show Status and their counts:")
print(av2017_data["Status"].value_counts(dropna=False))

print("\n Count of NaN values per column for COMPLETE cases:")
# filter the av2017_data dataframe to include only rows where the "Status" column is equal to "COMPLETE" and store the resulting dataframe in a variable called complete_cases
complete_cases = av2017_data[av2017_data["Status"] == "COMPLETE"] 
print(complete_cases.isnull().sum())

print("\n Show Cases where AdvocacyIssues is NaN:")
# filter the complete_cases dataframe to include only rows where the "AdvocacyIssues" column is NaN and print the resulting dataframe. 
# This will show all cases where the "AdvocacyIssues" variable is missing for complete cases.
print(complete_cases[complete_cases["AdvocacyIssues"].isnull()])

Number of duplicate rows in combined 2017 data: 0
Count of NaN values per column in 2017 Data:
Response ID                 0
Start Date                  0
End Date                    0
Status                      0
Source Type                 0
InteractPedestrian         34
InteractBicycle            34
CircumstancesCoded        583
FeelingsProvingGround      34
SafetyHuman                34
SafetyAV                   34
AVSafetyPotential          34
RegulationTesting          34
RegulationSpeed            34
RegulationSchoolZone       34
RegulationShareData        34
AdvocacyIssues             40
BikePghPosition            34
PayingAttentionAV          34
FamiliarityTechnoology     34
ZipCode                    34
BikePghMember               0
dtype: int64

 Show Status and their counts:
Status
COMPLETE      1120
INCOMPLETE      34
Name: count, dtype: int64

 Count of NaN values per column for COMPLETE cases:
Response ID                 0
Start Date                  0
End Date                    0
Status                      0
Source Type                 0
InteractPedestrian          0
InteractBicycle             0
CircumstancesCoded        549
FeelingsProvingGround       0
SafetyHuman                 0
SafetyAV                    0
AVSafetyPotential           0
RegulationTesting           0
RegulationSpeed             0
RegulationSchoolZone        0
RegulationShareData         0
AdvocacyIssues              6
BikePghPosition             0
PayingAttentionAV           0
FamiliarityTechnoology      0
ZipCode                     0
BikePghMember               0
dtype: int64

 Show Cases where AdvocacyIssues is NaN:
      Response ID                  Start Date                    End Date  \
397     260941817   03/07/2017 5:38:50 AM PST   03/07/2017 5:46:29 AM PST
434     260739659   03/01/2017 9:30:35 PM PST   03/08/2017 7:20:19 PM PST
601     260391263  02/24/2017 10:22:53 AM PST  02/24/2017 10:26:57 AM PST
1021    260889931   03/06/2017 6:19:01 AM PST   03/06/2017 6:25:43 AM PST
1026    260890082   03/06/2017 6:24:22 AM PST   03/06/2017 7:29:29 AM PST
1056    260895801   03/06/2017 9:53:26 AM PST   03/06/2017 9:57:14 AM PST

        Status  Source Type InteractPedestrian InteractBicycle  \
397   COMPLETE  Survey Link                Yes              No
434   COMPLETE  Survey Link                Yes              No
601   COMPLETE  Survey Link                Yes              No
1021  COMPLETE  Survey Link                 No              No
1026  COMPLETE  Survey Link                 No             Yes
1056  COMPLETE  Survey Link                 No              No

      CircumstancesCoded FeelingsProvingGround SafetyHuman  ...  \
397                  4.0            Disapprove           3  ...
434                  3.0            Disapprove           4  ...
601                  2.0      Somewhat Approve           3  ...
1021                 NaN   Somewhat Disapprove           2  ...
1026                 NaN               Approve           2  ...
1056                 NaN               Approve           2  ...

     RegulationTesting RegulationSpeed RegulationSchoolZone  \
397                Yes        Not sure                  Yes
434                Yes        Not sure                  Yes
601                Yes             Yes                  Yes
1021               Yes             Yes                  Yes
1026               Yes             Yes             Not sure
1056                No              No                   No

     RegulationShareData AdvocacyIssues             BikePghPosition  \
397                  Yes            NaN  Neither Support nor Oppose
434             Not sure            NaN             Actively Oppose
601                  Yes            NaN            Actively Support
1021                 Yes            NaN             Actively Oppose
1026                 Yes            NaN            Actively Support
1056                  No            NaN            Actively Support

         PayingAttentionAV FamiliarityTechnoology  ZipCode BikePghMember
397      To a large extent      Somewhat familiar  15215.0            no
434      To a large extent      Somewhat familiar  15212.0            no
601         To some extent      Mostly Unfamiliar  15207.0            no
1021  To a moderate extent      Somewhat familiar  15232.0            no
1026     To a large extent        Mostly familiar  15224.0            no
1056        To some extent      Somewhat familiar  15217.0            no

[6 rows x 22 columns]

## 2) Degradation Measurement of Robot Arm Position Accuracy

Create a unified dataset from all experimental files.

### 2a) Load all .csv files containing the raw data.

In [ ]:
path_raw_data = "data/robot_position_accuracy" 

path_raw_data = Path("data/robot_position_accuracy") # create a Path object from the path string using the Path() function from the pathlib library.

# Save all created dataframes from the csv-files in a dictionary with the name of the file as key and the dataframe as value
# we use a dictionary comprehension to create a dictionary called dfs 
# where the keys are the stem of the file names (i.e., the file name without the extension) 
# and the values are the dataframes created by reading each csv file in the path_raw_data directory using pandas read_csv function.
# The glob method is used to find all csv files in the directory.
dfs_raw = {f.stem: pd.read_csv(f) for f in path_raw_data.glob("ur5testresult_*.csv")} #prefix is important to avoid reading the wrong csv
print("\nDataframes created from csv files in robot_position_accuracy:")
# loop through the items in the dfs dictionary 
# and print the name of each dataframe (i.e., the key) and its shape 
for name, df in dfs_raw.items():
    print("Gespeicherte csv-Datei:", name, "  Shape:", df.shape)

Dataframes created from csv files in robot_position_accuracy:
Gespeicherte csv-Datei: ur5testresult_coldstart_fullspeed_payload4.5lb_1   Shape: (7009, 73)
Gespeicherte csv-Datei: ur5testresult_coldstart_fullspeed_payload4.5lb_2   Shape: (6930, 73)
Gespeicherte csv-Datei: ur5testresult_coldstart_fullspeed_payload4.5lb_3   Shape: (8798, 73)
Gespeicherte csv-Datei: ur5testresult_coldstart_halfspeed_payload4.5lb_1   Shape: (10321, 73)
Gespeicherte csv-Datei: ur5testresult_coldstart_halfspeed_payload4.5lb_2   Shape: (10358, 73)
Gespeicherte csv-Datei: ur5testresult_coldstart_halfspeed_payload4.5lb_3   Shape: (10276, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload1.6lb_1_1   Shape: (8662, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload1.6lb_2   Shape: (6792, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload1.6lb_3   Shape: (6979, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload4.5lb_1   Shape: (6932, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload4.5lb_2   Shape: (6486, 73)
Gespeicherte csv-Datei: ur5testresult_fullspeed_payload4.5lb_3   Shape: (8353, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload1.6lb_1   Shape: (7905, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload1.6lb_2   Shape: (7440, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload1.6lb_3   Shape: (10439, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload4.5lb_1   Shape: (10185, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload4.5lb_2   Shape: (9892, 73)
Gespeicherte csv-Datei: ur5testresult_halfspeed_payload4.5lb_3   Shape: (9883, 73)

### 2b) Extract relevant metadata from the filenames and add them in separate columns:
- Speed (e.g., HalfSpeed, FullSpeed)
- Load in lbs
- Cold start condition
- Trial number

In [20]:
import re
# loop through the items in the dfs dictionary and extract information from the file names using regular expressions (regex).
for name, df in dfs_raw.items():
    filename = name
    # use the re.match() function to match the filename against a regex pattern that captures 
    # the relevant information (coldstart, speed, payload, trial number) and store the matched groups in variables.
    #each bracketed part of the regex pattern corresponds to a group that captures a specific piece of information from the filename.
    match = re.match(r"ur5testresult_(coldstart_)?(fullspeed|halfspeed)_payload([\d.]+)lb_(\d+)", filename)
    # if the filename matches the expected pattern, extract the information and add it as new columns in the dataframe.
    if match:
        coldstart = match.group(1) is not None # check if the first group (coldstart) is present in the filename and store the result as a boolean in the variable coldstart
        speed = match.group(2) # extract the second group (speed) from the filename and store it in the variable speed (fullspeed or halfspeed)
        payload = float(match.group(3)) # extract the third group (payload) from the filename, convert it to a float, and store it in the variable payload
        trial_number = int(match.group(4)) # extract the fourth group (trial number) from the filename, convert it to an integer, and store it in the variable trial_number
        # Add the extracted information as new columns in the dataframe
        df["ColdStart"] = coldstart
        df["Speed"] = speed
        df["Payload_lb"] = payload
        df["TrialNumber"] = trial_number
        print(f"\n--- '{filename}' ---")
        print(f"ColdStart={coldstart}, Speed={speed}, Payload_lb={payload}, TrialNumber={trial_number}")
        #print(df.head())
    else:
        print(f"Filename '{filename}' does not match expected pattern.")
df.head()

# as you can see, the new columns "ColdStart", "Speed", "Payload_lb", and "TrialNumber" have been added
# the other columns using the first row of the dataframe as header.
# this problem will be fixed in the next steps

--- 'ur5testresult_coldstart_fullspeed_payload4.5lb_1' ---
ColdStart=True, Speed=fullspeed, Payload_lb=4.5, TrialNumber=1

--- 'ur5testresult_coldstart_fullspeed_payload4.5lb_2' ---
ColdStart=True, Speed=fullspeed, Payload_lb=4.5, TrialNumber=2

--- 'ur5testresult_coldstart_fullspeed_payload4.5lb_3' ---
ColdStart=True, Speed=fullspeed, Payload_lb=4.5, TrialNumber=3

--- 'ur5testresult_coldstart_halfspeed_payload4.5lb_1' ---
ColdStart=True, Speed=halfspeed, Payload_lb=4.5, TrialNumber=1

--- 'ur5testresult_coldstart_halfspeed_payload4.5lb_2' ---
ColdStart=True, Speed=halfspeed, Payload_lb=4.5, TrialNumber=2

--- 'ur5testresult_coldstart_halfspeed_payload4.5lb_3' ---
ColdStart=True, Speed=halfspeed, Payload_lb=4.5, TrialNumber=3

--- 'ur5testresult_fullspeed_payload1.6lb_1_1' ---
ColdStart=False, Speed=fullspeed, Payload_lb=1.6, TrialNumber=1

--- 'ur5testresult_fullspeed_payload1.6lb_2' ---
ColdStart=False, Speed=fullspeed, Payload_lb=1.6, TrialNumber=2

--- 'ur5testresult_fullspeed_payload1.6lb_3' ---
ColdStart=False, Speed=fullspeed, Payload_lb=1.6, TrialNumber=3

--- 'ur5testresult_fullspeed_payload4.5lb_1' ---
ColdStart=False, Speed=fullspeed, Payload_lb=4.5, TrialNumber=1

--- 'ur5testresult_fullspeed_payload4.5lb_2' ---
ColdStart=False, Speed=fullspeed, Payload_lb=4.5, TrialNumber=2

--- 'ur5testresult_fullspeed_payload4.5lb_3' ---
ColdStart=False, Speed=fullspeed, Payload_lb=4.5, TrialNumber=3

--- 'ur5testresult_halfspeed_payload1.6lb_1' ---
ColdStart=False, Speed=halfspeed, Payload_lb=1.6, TrialNumber=1

--- 'ur5testresult_halfspeed_payload1.6lb_2' ---
ColdStart=False, Speed=halfspeed, Payload_lb=1.6, TrialNumber=2

--- 'ur5testresult_halfspeed_payload1.6lb_3' ---
ColdStart=False, Speed=halfspeed, Payload_lb=1.6, TrialNumber=3

--- 'ur5testresult_halfspeed_payload4.5lb_1' ---
ColdStart=False, Speed=halfspeed, Payload_lb=4.5, TrialNumber=1

--- 'ur5testresult_halfspeed_payload4.5lb_2' ---
ColdStart=False, Speed=halfspeed, Payload_lb=4.5, TrialNumber=2

--- 'ur5testresult_halfspeed_payload4.5lb_3' ---
ColdStart=False, Speed=halfspeed, Payload_lb=4.5, TrialNumber=3

,([14142.928],[-28.237005518592152,-74.01719958583789,57.096445359825026,-162.0557312015655,-105.00878971089871,-44.72395360660826],[-28.236019331676722,-74.01801235708515,57.099507197092834,...,[27.78999137878418,29.429990768432617,29.299991607666016,34.20247268676758,34.255348205566406,35.86920928955078]),ColdStart,Speed,Payload_lb,TrialNumber
0,([14142.936],[-28.237005518592152,-74.0172,57.096445,-162.055731,-105.00879,-44.72395360660826],[-28.237385369510726,-74.018012,57.096775,...,[27.78999137878418,29.429991,29.299992,34.202473,34.255348,35.86920928955078]),False,halfspeed,4.5,3
1,([14142.944],[-28.237005518592152,-74.0172,57.096445,-162.055731,-105.00879,-44.72395360660826],[-28.23462597308604,-74.017329,57.100190,...,[27.78999137878418,29.429991,29.299992,34.202473,34.255348,35.86920928955078]),False,halfspeed,4.5,3
2,([14142.952],[-28.237005518592152,-74.0172,57.096445,-162.055731,-105.00879,-44.72395360660826],[-28.236702350593724,-74.018012,57.099507,...,[27.78999137878418,29.429991,29.299992,34.203224,34.255348,35.86920928955078]),False,halfspeed,4.5,3
3,([14142.96],[-28.237005518592152,-74.0172,57.096445,-162.055731,-105.00879,-44.72395360660826],[-28.235336312759724,-74.018695,57.098168,...,[27.78999137878418,29.429991,29.299992,34.203224,34.255348,35.86920928955078]),False,halfspeed,4.5,3
4,([14142.967999999999],[-28.237005518592152,-74.0172,57.096445,-162.055731,-105.00879,-44.72395360660826],[-28.231893897418036,-74.018695,57.099507,...,[27.78999137878418,29.429991,29.299992,34.203224,34.255348,35.86920928955078]),False,halfspeed,4.5,3

### 2c) Add column names from the master data.
Ensure consistent and easy-to-handle column names.

In [21]:
import re

# Load column names from master header file
header_df = pd.read_excel("data/robot_position_accuracy/ur5testresult_header.xlsx")
# save the column names from the header_df dataframe into a list called raw_col_names using the columns attribute and the tolist() method.
raw_col_names = header_df.columns.tolist()  # 73 column names

# Create clean, snake_case column names
def clean_col_name(col):
    # convert the column name to lowercase, remove parentheses, replace spaces and hyphens with underscores, and remove leading/trailing underscores.
    col = col.lower()
    col = col.replace("(", "").replace(")", "")
    col = re.sub(r"[\s\-]+", "_", col)
    col = re.sub(r"_+", "_", col)
    return col.strip("_")
# use a list comprehension to create a new list called clean_col_names by applying the clean_col_name function to each column name in the raw_col_names list.
clean_col_names = [clean_col_name(c) for c in raw_col_names]
print("Clean column names:")
#iterate through the raw_col_names and clean_col_names lists simultaneously using the zip() function and print each pair of raw and clean column names in a formatted way.

for raw, clean in zip(raw_col_names, clean_col_names):
    print(f"  {raw!r:50s} -> {clean!r}")

Clean column names:
  'ROBOT_TIME'                                       -> 'robot_time'
  'ROBOT_TARGET_JOINT_POSITIONS (J1)'                -> 'robot_target_joint_positions_j1'
  'ROBOT_TARGET_JOINT_POSITIONS (J2)'                -> 'robot_target_joint_positions_j2'
  'ROBOT_TARGET_JOINT_POSITIONS (J3)'                -> 'robot_target_joint_positions_j3'
  'ROBOT_TARGET_JOINT_POSITIONS (J4)'                -> 'robot_target_joint_positions_j4'
  'ROBOT_TARGET_JOINT_POSITIONS (J5)'                -> 'robot_target_joint_positions_j5'
  'ROBOT_TARGET_JOINT_POSITIONS (J6)'                -> 'robot_target_joint_positions_j6'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J1)'                -> 'robot_actual_joint_positions_j1'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J2)'                -> 'robot_actual_joint_positions_j2'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J3)'                -> 'robot_actual_joint_positions_j3'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J4)'                -> 'robot_actual_joint_positions_j4'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J5)'                -> 'robot_actual_joint_positions_j5'
  'ROBOT_ACTUAL_JOINT_POSITIONS (J6)'                -> 'robot_actual_joint_positions_j6'
  'ROBOT_TARGET_JOINT_VELOCITIES (J1)'               -> 'robot_target_joint_velocities_j1'
  'ROBOT_TARGET_JOINT_VELOCITIES (J2)'               -> 'robot_target_joint_velocities_j2'
  'ROBOT_TARGET_JOINT_VELOCITIES (J3)'               -> 'robot_target_joint_velocities_j3'
  'ROBOT_TARGET_JOINT_VELOCITIES (J4)'               -> 'robot_target_joint_velocities_j4'
  'ROBOT_TARGET_JOINT_VELOCITIES (J5)'               -> 'robot_target_joint_velocities_j5'
  'ROBOT_TARGET_JOINT_VELOCITIES (J6)'               -> 'robot_target_joint_velocities_j6'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J1)'               -> 'robot_actual_joint_velocities_j1'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J2)'               -> 'robot_actual_joint_velocities_j2'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J3)'               -> 'robot_actual_joint_velocities_j3'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J4)'               -> 'robot_actual_joint_velocities_j4'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J5)'               -> 'robot_actual_joint_velocities_j5'
  'ROBOT_ACTUAL_JOINT_VELOCITIES (J6)'               -> 'robot_actual_joint_velocities_j6'
  'ROBOT_TARGET_JOITN_CURRENT (J1)'                  -> 'robot_target_joitn_current_j1'
  'ROBOT_TARGET_JOITN_CURRENT (J2)'                  -> 'robot_target_joitn_current_j2'
  'ROBOT_TARGET_JOITN_CURRENT (J3)'                  -> 'robot_target_joitn_current_j3'
  'ROBOT_TARGET_JOITN_CURRENT (J4)'                  -> 'robot_target_joitn_current_j4'
  'ROBOT_TARGET_JOITN_CURRENT (J5)'                  -> 'robot_target_joitn_current_j5'
  'ROBOT_TARGET_JOITN_CURRENT (J6)'                  -> 'robot_target_joitn_current_j6'
  'ROBOT_ACTUAL_JOINT_CURRENT (J1)'                  -> 'robot_actual_joint_current_j1'
  'ROBOT_ACTUAL_JOINT_CURRENT (J2)'                  -> 'robot_actual_joint_current_j2'
  'ROBOT_ACTUAL_JOINT_CURRENT (J3)'                  -> 'robot_actual_joint_current_j3'
  'ROBOT_ACTUAL_JOINT_CURRENT (J4)'                  -> 'robot_actual_joint_current_j4'
  'ROBOT_ACTUAL_JOINT_CURRENT (J5)'                  -> 'robot_actual_joint_current_j5'
  'ROBOT_ACTUAL_JOINT_CURRENT (J6)'                  -> 'robot_actual_joint_current_j6'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J1)'            -> 'robot_target_joint_accelerations_j1'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J2)'            -> 'robot_target_joint_accelerations_j2'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J3)'            -> 'robot_target_joint_accelerations_j3'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J4)'            -> 'robot_target_joint_accelerations_j4'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J5)'            -> 'robot_target_joint_accelerations_j5'
  'ROBOT_TARGET_JOINT_ACCELERATIONS (J6)'            -> 'robot_target_joint_accelerations_j6'
  'ROBOT_TARGET_JOINT_TORQUES (J1)'                  -> 'robot_target_joint_torques_j1'
  'ROBOT_TARGET_JOINT_TORQUES (J2)'                  -> 'robot_target_joint_torques_j2'
  'ROBOT_TARGET_JOINT_TORQUES (J3)'                  -> 'robot_target_joint_torques_j3'
  'ROBOT_TARGET_JOINT_TORQUES (J4)'                  -> 'robot_target_joint_torques_j4'
  'ROBOT_TARGET_JOINT_TORQUES (J5)'                  -> 'robot_target_joint_torques_j5'
  'ROBOT_TARGET_JOINT_TORQUES (J6)'                  -> 'robot_target_joint_torques_j6'
  'ROBOT_JOINT_CONTROL_CURRENT (J1)'                 -> 'robot_joint_control_current_j1'
  'ROBOT_JOINT_CONTROL_CURRENT (J2)'                 -> 'robot_joint_control_current_j2'
  'ROBOT_JOINT_CONTROL_CURRENT (J3)'                 -> 'robot_joint_control_current_j3'
  'ROBOT_JOINT_CONTROL_CURRENT (J4)'                 -> 'robot_joint_control_current_j4'
  'ROBOT_JOINT_CONTROL_CURRENT (J5)'                 -> 'robot_joint_control_current_j5'
  'ROBOT_JOINT_CONTROL_CURRENT (J6)'                 -> 'robot_joint_control_current_j6'
  'ROBOT_CARTESIAN_COORD_TOOL (x)'                   -> 'robot_cartesian_coord_tool_x'
  'ROBOT_CARTESIAN_COORD_TOOL (y)'                   -> 'robot_cartesian_coord_tool_y'
  'ROBOT_CARTESIAN_COORD_TOOL (z)'                   -> 'robot_cartesian_coord_tool_z'
  'ROBOT_CARTESIAN_COORD_TOOL (rx)'                  -> 'robot_cartesian_coord_tool_rx'
  'ROBOT_CARTESIAN_COORD_TOOL (ry)'                  -> 'robot_cartesian_coord_tool_ry'
  'ROBOT_CARTESIAN_COORD_TOOL (rz)'                  -> 'robot_cartesian_coord_tool_rz'
  'ROBOT_TCP_FORCE (x)'                              -> 'robot_tcp_force_x'
  'ROBOT_TCP_FORCE (y)'                              -> 'robot_tcp_force_y'
  'ROBOT_TCP_FORCE (z)'                              -> 'robot_tcp_force_z'
  'ROBOT_TCP_FORCE (rx)'                             -> 'robot_tcp_force_rx'
  'ROBOT_TCP_FORCE (ry)'                             -> 'robot_tcp_force_ry'
  'ROBOT_TCP_FORCE (rz)'                             -> 'robot_tcp_force_rz'
  'ROBOT_JOINT_TEMP (J1)'                            -> 'robot_joint_temp_j1'
  'ROBOT_JOINT_TEMP (J2)'                            -> 'robot_joint_temp_j2'
  'ROBOT_JOINT_TEMP (J3)'                            -> 'robot_joint_temp_j3'
  'ROBOT_JOINT_TEMP (J4)'                            -> 'robot_joint_temp_j4'
  'ROBOT_JOINT_TEMP (J5)'                            -> 'robot_joint_temp_j5'
  'ROBOT_JOINT_TEMP (J6)'                            -> 'robot_joint_temp_j6'

In [22]:


# Reload all CSVs with correct column names (header=None, first row was data not header)
path_raw_data = Path("data/robot_position_accuracy")
# dictionary comprehension to create a dictionary called dfs 
# we load all csv files so that the first row is not treated as header but as data and we assign the clean column names from the header file-list(clean_col_names)
dfs = {f.stem: pd.read_csv(f, header=None, names=clean_col_names) for f in path_raw_data.glob("ur5testresult_*.csv")} 

# we loop through all dataframes in the dictionary and convert all columns with object dtype to numeric, removing any non-numeric characters
for df in dfs.values(): 
    # we loop through all columns in the dataframe that have the object data type using the select_dtypes() method and the include="object" argument.
    # for each column that has the object data type, we use the str.replace() method to remove any non-numeric characters (except for digits, decimal points, and hyphens) from the column values using a regular expression.
    # then we use the pd.to_numeric() function to convert the cleaned column values to numeric
    # example: if a column has values like "1.23222]]", the str.replace() method will remove the " ]]" part and leave "1.23", which can then be converted to a numeric value using pd.to_numeric().
    for col in df.select_dtypes(include="object").columns:
        df[col] = pd.to_numeric(
            df[col].str.replace(r"[^\d.\-]", "", regex=True),
            errors="coerce"
        )

# Re-apply metadata from filenames (2b)
# this step is necessary because we reloaded the csv files with header=None, so we need to re-extract the metadata from the filenames and add it as new columns in the dataframes.
for name, df in dfs.items():
    match = re.match(r"ur5testresult_(coldstart_)?(fullspeed|halfspeed)_payload([\d.]+)lb_(\d+)", name)
    if match:
        df["cold_start"]   = match.group(1) is not None
        df["speed"]        = match.group(2)
        df["payload_lb"]   = float(match.group(3))
        df["trial_number"] = int(match.group(4))

print(f"\nReloaded {len(dfs)} DataFrames with {len(clean_col_names)} named columns + 4 metadata columns.")
print("Example shape:", next(iter(dfs.values())).shape)
print("Example columns:", next(iter(dfs.values())).columns.tolist())
df.head()

Reloaded 18 DataFrames with 73 named columns + 4 metadata columns.
Example shape: (7010, 77)
Example columns: ['robot_time', 'robot_target_joint_positions_j1', 'robot_target_joint_positions_j2', 'robot_target_joint_positions_j3', 'robot_target_joint_positions_j4', 'robot_target_joint_positions_j5', 'robot_target_joint_positions_j6', 'robot_actual_joint_positions_j1', 'robot_actual_joint_positions_j2', 'robot_actual_joint_positions_j3', 'robot_actual_joint_positions_j4', 'robot_actual_joint_positions_j5', 'robot_actual_joint_positions_j6', 'robot_target_joint_velocities_j1', 'robot_target_joint_velocities_j2', 'robot_target_joint_velocities_j3', 'robot_target_joint_velocities_j4', 'robot_target_joint_velocities_j5', 'robot_target_joint_velocities_j6', 'robot_actual_joint_velocities_j1', 'robot_actual_joint_velocities_j2', 'robot_actual_joint_velocities_j3', 'robot_actual_joint_velocities_j4', 'robot_actual_joint_velocities_j5', 'robot_actual_joint_velocities_j6', 'robot_target_joitn_current_j1', 'robot_target_joitn_current_j2', 'robot_target_joitn_current_j3', 'robot_target_joitn_current_j4', 'robot_target_joitn_current_j5', 'robot_target_joitn_current_j6', 'robot_actual_joint_current_j1', 'robot_actual_joint_current_j2', 'robot_actual_joint_current_j3', 'robot_actual_joint_current_j4', 'robot_actual_joint_current_j5', 'robot_actual_joint_current_j6', 'robot_target_joint_accelerations_j1', 'robot_target_joint_accelerations_j2', 'robot_target_joint_accelerations_j3', 'robot_target_joint_accelerations_j4', 'robot_target_joint_accelerations_j5', 'robot_target_joint_accelerations_j6', 'robot_target_joint_torques_j1', 'robot_target_joint_torques_j2', 'robot_target_joint_torques_j3', 'robot_target_joint_torques_j4', 'robot_target_joint_torques_j5', 'robot_target_joint_torques_j6', 'robot_joint_control_current_j1', 'robot_joint_control_current_j2', 'robot_joint_control_current_j3', 'robot_joint_control_current_j4', 'robot_joint_control_current_j5', 'robot_joint_control_current_j6', 'robot_cartesian_coord_tool_x', 'robot_cartesian_coord_tool_y', 'robot_cartesian_coord_tool_z', 'robot_cartesian_coord_tool_rx', 'robot_cartesian_coord_tool_ry', 'robot_cartesian_coord_tool_rz', 'robot_tcp_force_x', 'robot_tcp_force_y', 'robot_tcp_force_z', 'robot_tcp_force_rx', 'robot_tcp_force_ry', 'robot_tcp_force_rz', 'robot_joint_temp_j1', 'robot_joint_temp_j2', 'robot_joint_temp_j3', 'robot_joint_temp_j4', 'robot_joint_temp_j5', 'robot_joint_temp_j6', 'cold_start', 'speed', 'payload_lb', 'trial_number']

,robot_time,robot_target_joint_positions_j1,robot_target_joint_positions_j2,robot_target_joint_positions_j3,robot_target_joint_positions_j4,robot_target_joint_positions_j5,robot_target_joint_positions_j6,robot_actual_joint_positions_j1,robot_actual_joint_positions_j2,robot_actual_joint_positions_j3,...,robot_joint_temp_j1,robot_joint_temp_j2,robot_joint_temp_j3,robot_joint_temp_j4,robot_joint_temp_j5,robot_joint_temp_j6,cold_start,speed,payload_lb,trial_number
0,14142.928,-28.237006,-74.0172,57.096445,-162.055731,-105.00879,-44.723954,-28.236019,-74.018012,57.099507,...,27.789991,29.429991,29.299992,34.202473,34.255348,35.869209,False,halfspeed,4.5,3
1,14142.936,-28.237006,-74.0172,57.096445,-162.055731,-105.00879,-44.723954,-28.237385,-74.018012,57.096775,...,27.789991,29.429991,29.299992,34.202473,34.255348,35.869209,False,halfspeed,4.5,3
2,14142.944,-28.237006,-74.0172,57.096445,-162.055731,-105.00879,-44.723954,-28.234626,-74.017329,57.100190,...,27.789991,29.429991,29.299992,34.202473,34.255348,35.869209,False,halfspeed,4.5,3
3,14142.952,-28.237006,-74.0172,57.096445,-162.055731,-105.00879,-44.723954,-28.236702,-74.018012,57.099507,...,27.789991,29.429991,29.299992,34.203224,34.255348,35.869209,False,halfspeed,4.5,3
4,14142.960,-28.237006,-74.0172,57.096445,-162.055731,-105.00879,-44.723954,-28.235336,-74.018695,57.098168,...,27.789991,29.429991,29.299992,34.203224,34.255348,35.869209,False,halfspeed,4.5,3

2d Combine all files into a single DataFrame with metadata columns and correct
indexes.

In [23]:

# we use the concat() function from pandas to combine all the dataframes in the dfs dictionary into a single dataframe called df_combined.
df_combined = pd.concat(dfs.values(), ignore_index=True)
print("Combined DataFrame shape:", df_combined.shape)
print("Index:", df_combined.index)
df_combined.head()

Combined DataFrame shape: (153658, 77)
Index: RangeIndex(start=0, stop=153658, step=1)

,robot_time,robot_target_joint_positions_j1,robot_target_joint_positions_j2,robot_target_joint_positions_j3,robot_target_joint_positions_j4,robot_target_joint_positions_j5,robot_target_joint_positions_j6,robot_actual_joint_positions_j1,robot_actual_joint_positions_j2,robot_actual_joint_positions_j3,...,robot_joint_temp_j1,robot_joint_temp_j2,robot_joint_temp_j3,robot_joint_temp_j4,robot_joint_temp_j5,robot_joint_temp_j6,cold_start,speed,payload_lb,trial_number
0,747.248,-26.880069,-79.911609,57.095392,-157.771764,-105.009613,-44.724779,-26.876620,-79.910908,57.096775,...,25.209991,26.714735,26.712410,29.805393,28.690552,29.992847,True,fullspeed,4.5,1
1,747.256,-26.880069,-79.911609,57.095392,-157.771764,-105.009613,-44.724779,-26.876620,-79.910225,57.096092,...,25.209991,26.714735,26.712410,29.805393,28.690552,29.992847,True,fullspeed,4.5,1
2,747.264,-26.880069,-79.911609,57.095392,-157.771764,-105.009613,-44.724779,-26.879380,-79.909542,57.097485,...,25.209991,26.714735,26.712410,29.805393,28.690552,29.992847,True,fullspeed,4.5,1
3,747.272,-26.880069,-79.911609,57.095392,-157.771764,-105.009613,-44.724779,-26.879380,-79.910908,57.096092,...,25.209991,26.714735,26.712410,29.805393,28.690552,29.992847,True,fullspeed,4.5,1
4,747.280,-26.880069,-79.911609,57.095392,-157.771764,-105.009613,-44.724779,-26.877303,-79.909542,57.096775,...,25.209991,26.714735,26.714169,29.805393,28.691496,29.993563,True,fullspeed,4.5,1

### 2e) Store the resulting data frame as parquet.
Ensure that the schema contains correct data types for all columns.

In [24]:
pd.set_option("display.max_rows", None)
print(df_combined.dtypes)
pd.reset_option("display.max_rows")

robot_time                             float64
robot_target_joint_positions_j1        float64
robot_target_joint_positions_j2        float64
robot_target_joint_positions_j3        float64
robot_target_joint_positions_j4        float64
robot_target_joint_positions_j5        float64
robot_target_joint_positions_j6        float64
robot_actual_joint_positions_j1        float64
robot_actual_joint_positions_j2        float64
robot_actual_joint_positions_j3        float64
robot_actual_joint_positions_j4        float64
robot_actual_joint_positions_j5        float64
robot_actual_joint_positions_j6        float64
robot_target_joint_velocities_j1       float64
robot_target_joint_velocities_j2       float64
robot_target_joint_velocities_j3       float64
robot_target_joint_velocities_j4       float64
robot_target_joint_velocities_j5       float64
robot_target_joint_velocities_j6       float64
robot_actual_joint_velocities_j1       float64
robot_actual_joint_velocities_j2       float64
robot_actual_joint_velocities_j3       float64
robot_actual_joint_velocities_j4       float64
robot_actual_joint_velocities_j5       float64
robot_actual_joint_velocities_j6       float64
robot_target_joitn_current_j1          float64
robot_target_joitn_current_j2          float64
robot_target_joitn_current_j3          float64
robot_target_joitn_current_j4          float64
robot_target_joitn_current_j5          float64
robot_target_joitn_current_j6          float64
robot_actual_joint_current_j1          float64
robot_actual_joint_current_j2          float64
robot_actual_joint_current_j3          float64
robot_actual_joint_current_j4          float64
robot_actual_joint_current_j5          float64
robot_actual_joint_current_j6          float64
robot_target_joint_accelerations_j1    float64
robot_target_joint_accelerations_j2    float64
robot_target_joint_accelerations_j3    float64
robot_target_joint_accelerations_j4    float64
robot_target_joint_accelerations_j5    float64
robot_target_joint_accelerations_j6    float64
robot_target_joint_torques_j1          float64
robot_target_joint_torques_j2          float64
robot_target_joint_torques_j3          float64
robot_target_joint_torques_j4          float64
robot_target_joint_torques_j5          float64
robot_target_joint_torques_j6          float64
robot_joint_control_current_j1         float64
robot_joint_control_current_j2         float64
robot_joint_control_current_j3         float64
robot_joint_control_current_j4         float64
robot_joint_control_current_j5         float64
robot_joint_control_current_j6         float64
robot_cartesian_coord_tool_x           float64
robot_cartesian_coord_tool_y           float64
robot_cartesian_coord_tool_z           float64
robot_cartesian_coord_tool_rx          float64
robot_cartesian_coord_tool_ry          float64
robot_cartesian_coord_tool_rz          float64
robot_tcp_force_x                      float64
robot_tcp_force_y                      float64
robot_tcp_force_z                      float64
robot_tcp_force_rx                     float64
robot_tcp_force_ry                     float64
robot_tcp_force_rz                     float64
robot_joint_temp_j1                    float64
robot_joint_temp_j2                    float64
robot_joint_temp_j3                    float64
robot_joint_temp_j4                    float64
robot_joint_temp_j5                    float64
robot_joint_temp_j6                    float64
cold_start                                bool
speed                                   object
payload_lb                             float64
trial_number                             int64
dtype: object

In [25]:
!pip install fastparquet
# we save the combined dataframe to a parquet file using the to_parquet() method from pandas and specify the engine as "fastparquet".
df_combined.to_parquet("data/robot_position_accuracy/ur5_combined.parquet", engine="fastparquet")

Requirement already satisfied: fastparquet in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (2024.11.0)
Requirement already satisfied: packaging in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from fastparquet) (26.0)
Requirement already satisfied: cramjam>=2.3 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from fastparquet) (2025.10.0)
Requirement already satisfied: numpy in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from fastparquet) (2.0.2)
Requirement already satisfied: pandas>=1.5.0 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from pandas>=1.5.0->fastparquet) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\athit\onedrive\dokumente\th nürnberg\1.semester\data analytics\data analytics lab\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\athit\OneDrive\Dokumente\Th Nürnberg\1.Semester\Data Analytics\Data Analytics Lab\venv\Scripts\python.exe -m pip install --upgrade pip' command.

### 2f) Bonus: Store the resulting data frame as csv and compare the time required to read both data sets.
Use e.g. the `time` package.

In [13]:
import time


df_combined.to_csv("data/robot_position_accuracy/ur5_combined.csv", index=False)

# parquet reading time
# set time before reading the parquet file using the time() function from the time module and store it in a variable called start.
start = time.time()
# read the parquet file using the read_parquet() function from pandas and specify the engine as "fastparquet". This will load the data from the parquet file into a dataframe.
pd.read_parquet("data/robot_position_accuracy/ur5_combined.parquet", engine="fastparquet")
# calculate the time taken to read the parquet file by subtracting the start time from the current time using the time() function again and store the result in a variable called parquet_time.
parquet_time = time.time() - start

# csv rading time
#repeat the same process for the csv file: set the start time, read the csv file using read_csv(), and calculate the time taken to read the csv file.
start = time.time()
pd.read_csv("data/robot_position_accuracy/ur5_combined.csv")
csv_time = time.time() - start

print(f"Parquet: {parquet_time:.3f}s")
print(f"CSV:     {csv_time:.3f}s")
print(f"Parquet ist {csv_time / parquet_time:.1f}x faster")

Parquet: 0.184s
CSV:     2.764s
Parquet ist 15.1x faster